on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy src folder
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: files.000webhost.com
        username: cs-departement-management
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./src/
        server-dir: public_html/

  web-deploy-includes:
    name: 🎉 Deploy includes folder
    needs: web-deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: files.000webhost.com
        username: cs-departement-management
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./includes/
        server-dir: includes/

  web-deploy-database:
    name: 🎉 Deploy database folder
    needs: web-deploy-includes
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: files.000webhost.com
        username: cs-departement-management
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./database/
        server-dir: database/